// ============================================================
// INFINITY SKILLS - Mock Data Layer
// In production, replace with Prisma/Drizzle ORM + PostgreSQL
// ============================================================

import { Service, Course, Task } from '@/types';

export const services: Service[] = [
  {
    id: 'svc-001',
    title: 'Skill Development Courses',
    description: 'Master in-demand skills with structured learning paths designed for students from Class 6 to 12. From coding to communication, build your future today.',
    category: 'skill-development',
    icon: 'Rocket',
    color: 'from-blue-500 to-indigo-600',
    features: [
      'Programming & Web Development',
      'Public Speaking & Communication',
      'Critical Thinking & Problem Solving',
      'Digital Literacy & AI Basics',
      'Leadership & Teamwork',
      'Time Management & Productivity'
    ],
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    coursesCount: 45,
  },
  {
    id: 'svc-002',
    title: 'Course Guidance',
    description: 'Get personalized course recommendations based on your interests, strengths, and career goals. Navigate your learning journey with expert guidance.',
    category: 'course-guidance',
    icon: 'Compass',
    color: 'from-emerald-500 to-teal-600',
    features: [
      'Personalized Learning Paths',
      'Subject Selection Guidance',
      'Stream Selection (Science/Commerce/Arts)',
      'Competitive Exam Preparation',
      'Board Exam Strategies',
      'Study Planning & Scheduling'
    ],
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    coursesCount: 32,
  },
  {
    id: 'svc-003',
    title: 'Career Guidance',
    description: 'Explore diverse career options, understand industry requirements, and plan your path from school to professional success.',
    category: 'career-guidance',
    icon: 'Target',
    color: 'from-purple-500 to-violet-600',
    features: [
      'Career Aptitude Assessment',
      'Industry Exploration Sessions',
      'Mentorship Programs',
      'Resume & Portfolio Building',
      'Interview Preparation',
      'Internship Opportunities'
    ],
    targetClasses: [8, 9, 10, 11, 12],
    coursesCount: 28,
  },
  {
    id: 'svc-004',
    title: 'Entrepreneurship',
    description: 'Learn the fundamentals of building businesses, developing products, and creating value. Start your entrepreneurial journey early.',
    category: 'entrepreneurship',
    icon: 'Lightbulb',
    color: 'from-orange-500 to-amber-600',
    features: [
      'Business Idea Generation',
      'Startup Basics & Lean Canvas',
      'Marketing & Branding',
      'Product Development',
      'Pitch Deck Creation',
      'Young Entrepreneurs Club'
    ],
    targetClasses: [8, 9, 10, 11, 12],
    coursesCount: 20,
  },
  {
    id: 'svc-005',
    title: 'Finance & Money Skills',
    description: 'Build financial literacy from an early age. Learn saving, investing, budgeting, and understanding the economy.',
    category: 'finance',
    icon: 'TrendingUp',
    color: 'from-green-500 to-emerald-600',
    features: [
      'Personal Finance Basics',
      'Saving & Budgeting',
      'Introduction to Investing',
      'Understanding Stock Market',
      'Financial Goal Setting',
      'Money Management Games'
    ],
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    coursesCount: 18,
  },
  {
    id: 'svc-006',
    title: 'Art & Craft',
    description: 'Express your creativity through various art forms. From digital art to traditional crafts, discover your artistic potential.',
    category: 'art-craft',
    icon: 'Palette',
    color: 'from-pink-500 to-rose-600',
    features: [
      'Digital Art & Design',
      'Painting & Sketching',
      'DIY Crafts & Projects',
      'Photography Basics',
      'Creative Writing',
      'Music & Performing Arts'
    ],
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    coursesCount: 25,
  },
];

export const courses: Course[] = [
  {
    id: 'crs-001',
    title: 'Python Programming for Beginners',
    description: 'Start your coding journey with Python. Learn variables, loops, functions, and build real projects.',
    thumbnail: '/api/placeholder/400/250',
    category: 'skill-development',
    level: 'beginner',
    duration: '8 weeks',
    lessons: 32,
    enrolled: 1245,
    rating: 4.8,
    instructor: 'Dr. Anil Kumar',
    targetClasses: [8, 9, 10, 11, 12],
    tags: ['coding', 'python', 'programming'],
    status: 'published',
    modules: [
      {
        id: 'mod-001',
        title: 'Getting Started with Python',
        description: 'Install Python, set up your environment, and write your first program.',
        order: 1,
        lessons: [
          { id: 'les-001', title: 'What is Programming?', type: 'video', duration: '12 min', completed: true },
          { id: 'les-002', title: 'Installing Python', type: 'article', duration: '8 min', completed: true },
          { id: 'les-003', title: 'Your First Python Program', type: 'video', duration: '15 min', completed: false },
          { id: 'les-004', title: 'Quiz: Python Basics', type: 'quiz', duration: '10 min', completed: false },
        ],
      },
      {
        id: 'mod-002',
        title: 'Variables and Data Types',
        description: 'Learn about different types of data and how to store them.',
        order: 2,
        lessons: [
          { id: 'les-005', title: 'Numbers & Strings', type: 'video', duration: '18 min', completed: false },
          { id: 'les-006', title: 'Lists & Dictionaries', type: 'video', duration: '20 min', completed: false },
          { id: 'les-007', title: 'Practice Project', type: 'project', duration: '45 min', completed: false },
        ],
      },
    ],
    createdAt: '2024-01-15',
  },
  {
    id: 'crs-002',
    title: 'Public Speaking Mastery',
    description: 'Overcome stage fear and become a confident speaker. Perfect for school presentations and competitions.',
    thumbnail: '/api/placeholder/400/250',
    category: 'skill-development',
    level: 'beginner',
    duration: '4 weeks',
    lessons: 16,
    enrolled: 892,
    rating: 4.7,
    instructor: 'Ms. Priya Sharma',
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    tags: ['communication', 'speaking', 'confidence'],
    status: 'published',
    modules: [],
    createdAt: '2024-02-10',
  },
  {
    id: 'crs-003',
    title: 'Choose Your Stream: Science vs Commerce vs Arts',
    description: 'A comprehensive guide to help you make the right choice after Class 10.',
    thumbnail: '/api/placeholder/400/250',
    category: 'course-guidance',
    level: 'beginner',
    duration: '2 weeks',
    lessons: 12,
    enrolled: 2100,
    rating: 4.9,
    instructor: 'Career Counseling Team',
    targetClasses: [9, 10],
    tags: ['stream-selection', 'career', 'guidance'],
    status: 'published',
    modules: [],
    createdAt: '2024-01-20',
  },
  {
    id: 'crs-004',
    title: 'JEE/NEET Preparation Roadmap',
    description: 'Strategic planning and resource guidance for competitive exam preparation.',
    thumbnail: '/api/placeholder/400/250',
    category: 'course-guidance',
    level: 'intermediate',
    duration: '6 weeks',
    lessons: 24,
    enrolled: 3200,
    rating: 4.6,
    instructor: 'Prof. Rajesh Verma',
    targetClasses: [11, 12],
    tags: ['jee', 'neet', 'competitive-exams'],
    status: 'published',
    modules: [],
    createdAt: '2024-03-01',
  },
  {
    id: 'crs-005',
    title: 'Discover Your Career Path',
    description: 'Explore 50+ career options with real-world insights from industry professionals.',
    thumbnail: '/api/placeholder/400/250',
    category: 'career-guidance',
    level: 'beginner',
    duration: '3 weeks',
    lessons: 15,
    enrolled: 1500,
    rating: 4.8,
    instructor: 'Career Team',
    targetClasses: [8, 9, 10, 11, 12],
    tags: ['career', 'exploration', 'guidance'],
    status: 'published',
    modules: [],
    createdAt: '2024-02-15',
  },
  {
    id: 'crs-006',
    title: 'Young Entrepreneur Bootcamp',
    description: 'Learn to think like an entrepreneur. Build your first business idea from scratch.',
    thumbnail: '/api/placeholder/400/250',
    category: 'entrepreneurship',
    level: 'beginner',
    duration: '6 weeks',
    lessons: 20,
    enrolled: 750,
    rating: 4.7,
    instructor: 'Mr. Vikram Singh',
    targetClasses: [9, 10, 11, 12],
    tags: ['startup', 'business', 'entrepreneurship'],
    status: 'published',
    modules: [],
    createdAt: '2024-03-10',
  },
  {
    id: 'crs-007',
    title: 'Money Smart: Financial Literacy for Teens',
    description: 'Learn saving, budgeting, and basic investing concepts in a fun and engaging way.',
    thumbnail: '/api/placeholder/400/250',
    category: 'finance',
    level: 'beginner',
    duration: '4 weeks',
    lessons: 18,
    enrolled: 980,
    rating: 4.5,
    instructor: 'Ms. Neha Gupta',
    targetClasses: [6, 7, 8, 9, 10],
    tags: ['finance', 'money', 'saving'],
    status: 'published',
    modules: [],
    createdAt: '2024-02-28',
  },
  {
    id: 'crs-008',
    title: 'Digital Art & Design Fundamentals',
    description: 'Create stunning digital artwork using free tools. From basics to advanced techniques.',
    thumbnail: '/api/placeholder/400/250',
    category: 'art-craft',
    level: 'beginner',
    duration: '5 weeks',
    lessons: 22,
    enrolled: 1100,
    rating: 4.8,
    instructor: 'Mr. Arjun Patel',
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    tags: ['art', 'digital-art', 'design'],
    status: 'published',
    modules: [],
    createdAt: '2024-01-25',
  },
  {
    id: 'crs-009',
    title: 'Web Development with HTML, CSS & JavaScript',
    description: 'Build real websites from scratch. Perfect project-based learning for young developers.',
    thumbnail: '/api/placeholder/400/250',
    category: 'skill-development',
    level: 'intermediate',
    duration: '10 weeks',
    lessons: 40,
    enrolled: 2300,
    rating: 4.9,
    instructor: 'Mr. Karan Mehta',
    targetClasses: [9, 10, 11, 12],
    tags: ['web', 'html', 'css', 'javascript'],
    status: 'published',
    modules: [],
    createdAt: '2024-03-05',
  },
  {
    id: 'crs-010',
    title: 'Creative Writing Workshop',
    description: 'Develop your writing skills - stories, poems, essays, and blogs.',
    thumbnail: '/api/placeholder/400/250',
    category: 'art-craft',
    level: 'beginner',
    duration: '4 weeks',
    lessons: 16,
    enrolled: 670,
    rating: 4.6,
    instructor: 'Ms. Anita Roy',
    targetClasses: [6, 7, 8, 9, 10, 11, 12],
    tags: ['writing', 'creative', 'stories'],
    status: 'published',
    modules: [],
    createdAt: '2024-02-20',
  },
];

export const tasks: Task[] = [
  {
    id: 'tsk-001',
    title: 'Complete Python Chapter 3 Exercises',
    description: 'Solve all 10 exercises from the Variables & Data Types chapter.',
    category: 'skill-development',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2024-04-15',
    tags: ['python', 'coding', 'practice'],
    subtasks: [
      { id: 'st-001', title: 'Exercise 1-3: Basic Variables', completed: true },
      { id: 'st-002', title: 'Exercise 4-6: String Operations', completed: true },
      { id: 'st-003', title: 'Exercise 7-8: Lists', completed: false },
      { id: 'st-004', title: 'Exercise 9-10: Dictionaries', completed: false },
    ],
    createdAt: '2024-04-10',
  },
  {
    id: 'tsk-002',
    title: 'Prepare Speech for School Competition',
    description: 'Write and practice a 5-minute speech on "Technology and Youth".',
    category: 'skill-development',
    priority: 'urgent',
    status: 'todo',
    dueDate: '2024-04-12',
    tags: ['speaking', 'competition', 'practice'],
    subtasks: [
      { id: 'st-005', title: 'Research the topic', completed: false },
      { id: 'st-006', title: 'Write the speech draft', completed: false },
      { id: 'st-007', title: 'Practice delivery (3 times)', completed: false },
    ],
    createdAt: '2024-04-08',
  },
  {
    id: 'tsk-003',
    title: 'Complete Career Assessment Quiz',
    description: 'Take the aptitude test to discover suitable career paths.',
    category: 'career-guidance',
    priority: 'medium',
    status: 'todo',
    dueDate: '2024-04-20',
    tags: ['career', 'assessment', 'aptitude'],
    subtasks: [
      { id: 'st-008', title: 'Complete interest inventory', completed: false },
      { id: 'st-009', title: 'Complete aptitude test', completed: false },
      { id: 'st-010', title: 'Review results with counselor', completed: false },
    ],
    createdAt: '2024-04-09',
  },
  {
    id: 'tsk-004',
    title: 'Business Plan Draft - Recycled Crafts',
    description: 'Create a one-page business plan for the eco-friendly crafts startup idea.',
    category: 'entrepreneurship',
    priority: 'medium',
    status: 'todo',
    dueDate: '2024-04-25',
    tags: ['business', 'startup', 'plan'],
    subtasks: [
      { id: 'st-011', title: 'Define target customers', completed: false },
      { id: 'st-012', title: 'List products/services', completed: false },
      { id: 'st-013', title: 'Calculate startup costs', completed: false },
      { id: 'st-014', title: 'Write value proposition', completed: false },
    ],
    createdAt: '2024-04-11',
  },
  {
    id: 'tsk-005',
    title: 'Monthly Budget Tracking Exercise',
    description: 'Track all expenses for this month and categorize them.',
    category: 'finance',
    priority: 'low',
    status: 'in-progress',
    dueDate: '2024-04-30',
    tags: ['finance', 'budget', 'tracking'],
    subtasks: [
      { id: 'st-015', title: 'Set up budget spreadsheet', completed: true },
      { id: 'st-016', title: 'Record daily expenses', completed: false },
      { id: 'st-017', title: 'Categorize all expenses', completed: false },
      { id: 'st-018', title: 'Calculate savings rate', completed: false },
    ],
    createdAt: '2024-04-01',
  },
  {
    id: 'tsk-006',
    title: 'Digital Art Portfolio - 5 Pieces',
    description: 'Create 5 digital art pieces for your portfolio using Canva/Figma.',
    category: 'art-craft',
    priority: 'medium',
    status: 'in-progress',
    dueDate: '2024-04-28',
    tags: ['art', 'portfolio', 'digital'],
    subtasks: [
      { id: 'st-019', title: 'Landscape illustration', completed: true },
      { id: 'st-020', title: 'Character design', completed: true },
      { id: 'st-021', title: 'Abstract composition', completed: false },
      { id: 'st-022', title: 'Typography poster', completed: false },
      { id: 'st-023', title: 'UI mockup design', completed: false },
    ],
    createdAt: '2024-04-05',
  },
];

// Helper functions for data access (simulating database queries)
export function getServiceByCategory(category: string): Service | undefined {
  return services.find(s => s.category === category);
}

export function getCoursesByCategory(category: string): Course[] {
  return courses.filter(c => c.category === category);
}

export function getCourseById(id: string): Course | undefined {
  return courses.find(c => c.id === id);
}

export function getTasksByCategory(category: string): Task[] {
  return tasks.filter(t => t.category === category);
}

export function getTasksByStatus(status: string): Task[] {
  return tasks.filter(t => t.status === status);
}
